### PR TITLE
Fixed bug when API key is missing

### LINKED ISSUE #159: Videogames nolonger searchable
-   [x] The Plugin is up to date - 0.7.2
-   [x] Obsidian is up to date - V1.6.7

**Describe the bug**
When I activate the Media DB Video Game search, enter a title and press ok the modals go away and no search results are seen.

**To Reproduce**

1. Open Command Palette and search for game to select `Media DB: Create Media DB entry (Game)`
2. Search for a title: Fable
3. Press enter or hit OK
4. See no search results

**Expected behavior**

I expected to see search results for various titles the API thinks I am looking for like when I search for books, music, or TV shows (all of which work as expected).

**Screenshots**

Music:
image

Book:
image

TV Series:
image

**Occurs on**

-   [x] Linux

**Plugin version**
0.7.2

### PR DESCRIPTION
**Pull request by ltctceplrm**
To fix #159.

Ideally at one point the user should be notified with a message box that he's missing an API but for now this should be good enough

### CODE REVIEW

File: src/api/apis/OMDbAPI.ts [hunk 1]
```diff
@@ -29,7 +29,8 @@ export class OMDbAPI extends APIModel {
 		console.log(`MDB | api "${this.apiName}" queried by Title`);
 
 		if (!this.plugin.settings.OMDbKey) {
-			throw Error(`MDB | API key for ${this.apiName} missing.`);
+			console.error(Error(`MDB | API key for ${this.apiName} missing.`));
```
Comment (mProjectsCode) [inline src/api/apis/OMDbAPI.ts:32]: The change for getById is missing.

File: src/api/apis/MobyGamesAPI.ts [hunk 2]
```diff
@@ -65,7 +66,7 @@ export class MobyGamesAPI extends APIModel {
 		console.log(`MDB | api "${this.apiName}" queried by ID`);
 
 		if (!this.plugin.settings.MobyGamesKey) {
-			throw Error(`MDB | API key for ${this.apiName} missing.`);
+			console.log(Error(`MDB | API key for ${this.apiName} missing.`));
```
Comment (mProjectsCode) [inline src/api/apis/MobyGamesAPI.ts:69]: This should exit the function here.

**Review by mProjectsCode — COMMENTED** [review]
It might be good to also show the user a notice, instead of just printing something to the console.

**Comment by mProjectsCode** [comment]
You should construct errors with the constructor, so `new Error(...)` instead of `Error(...)`

File: src/api/apis/MobyGamesAPI.ts (hunk 2 above)
Comment (ltctceplrm) [reply src/api/apis/MobyGamesAPI.ts:69]: Oh yes that's an oversight, I was testing some things and forgot to change that one back.

File: src/api/apis/OMDbAPI.ts (hunk 1 above)
Comment (ltctceplrm) [reply src/api/apis/OMDbAPI.ts:32]: Actually I left the getById as it was because it is supposed to fail when it's missing that specific API key. I can't have it return an empty array since it would give an error (Type 'undefined[]' is missing the following properties from type 'MediaTypeModel': type, subType, title, englishTitle, and 10 more).

Ideally rather than silently fail it would give the user a message box saying why it failed.
Originally this PR was intended as just a bug fix for video game searches but I don't mind expanding it to also adding a visible error message. Would it be alright to just make a new Modal for warnings/errors based on the PreviewModal?

Comment (mProjectsCode) [reply src/api/apis/OMDbAPI.ts]: > Would it be alright to just make a new Modal for warnings/errors based on the PreviewModal?

I would use Obsidians `Notice` to give a small push notification. An entire modal seems overkill.

Comment (ltctceplrm) [reply src/api/apis/OMDbAPI.ts]: Oh wow I never knew about that function, that was very easy to add.

**Comment by ltctceplrm** [comment]
Thank you for merging the PRs!
